<?php
namespace App\Http\Controllers;
use App\Services\Workflow;
use Illuminate\Routing\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class LogisticsController extends Controller {
 public function landing(){if(auth()->check())return redirect('/dashboard');return view('landing',['stats'=>['delivered'=>DB::table('parcels')->whereIn('status',['DELIVERED','COMPLETED'])->count(),'riders'=>DB::table('users')->where('role','rider')->where('approval_status','approved')->where('active',1)->count(),'areas'=>DB::table('delivery_areas')->count(),'centers'=>DB::table('sorting_centers')->count()]]);}
 public function track(Request $r){$code=trim((string)$r->query('code'));$parcel=null;$events=collect();if($code!==''){$parcel=DB::table('parcels as p')->join('orders as o','o.id','=','p.order_id')->join('addresses as a','a.id','=','o.address_id')->where('p.tracking_code',$code)->select('p.id','p.tracking_code','p.status','a.city','a.province')->first();if($parcel)$events=DB::table('status_history')->where('parcel_id',$parcel->id)->orderBy('id')->get(['to_status','created_at']);}return view('track',compact('code','parcel','events'));}
 private function listing($title,$q){return view('list',['title'=>$title,'links'=>app(CommonController::class)->links(),'records'=>$q->orderByDesc('id')->paginate(30)]);}
 private function centerId(){return DB::table('sorting_centers')->where('user_id',auth()->id())->value('id');}
 public function approvals(){$users=DB::table('users')->where('role','rider')->where('approval_status','pending')->paginate(20);return view('center_approvals',['links'=>app(CommonController::class)->links(),'users'=>$users,'docs'=>DB::table('registration_documents')->whereIn('user_id',$users->pluck('id'))->get()->groupBy('user_id')]);}
 public function document(int $id){$d=DB::table('registration_documents')->join('users','users.id','=','registration_documents.user_id')->where('registration_documents.id',$id)->where('users.role','rider')->select('registration_documents.*')->first();abort_unless($d,404);return response()->file(storage_path('app/private/'.$d->path));}
 public function approve(Request $r,int $id){$v=$r->validate(['decision'=>'required|in:approved,rejected']);abort_unless(DB::table('users')->where('id',$id)->where('role','rider')->where('approval_status','pending')->update(['approval_status'=>$v['decision'],'updated_at'=>now()]),422);return back()->with('success','Decision saved.');}
 public function areas(){return view('center_areas',['links'=>app(CommonController::class)->links(),'areas'=>DB::table('delivery_areas')->where('center_id',$this->centerId())->get(),'riders'=>DB::table('users')->where('role','rider')->where('active',1)->where('approval_status','approved')->get()]);}
 public function area(Request $r){$v=$r->validate(['name'=>'required|max:150','city'=>'required|max:120','province'=>'required|max:120','rider_id'=>'required|exists:users,id']);abort_unless(DB::table('users')->where('id',$v['rider_id'])->where('role','rider')->where('approval_status','approved')->where('active',1)->exists(),422);DB::table('delivery_areas')->insert($v+['center_id'=>$this->centerId(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Area added.');}
 public function pickups(){return view('center_pickups',['links'=>app(CommonController::class)->links(),'requests'=>DB::table('assignments as s')->join('parcels as p','p.id','=','s.parcel_id')->join('orders as o','o.id','=','p.order_id')->join('addresses as a','a.id','=','o.address_id')->where('s.kind','pickup')->where('s.status','requested')->whereNull('p.center_id')->select('s.*','p.tracking_code','a.city','a.province')->paginate(20)]);}
 public function verifyPickup(int $id){$a=DB::table('assignments')->where('id',$id)->where('kind','pickup')->where('status','requested')->first();abort_unless($a,404);DB::transaction(function()use($id,$a){DB::table('parcels')->where('id',$a->parcel_id)->whereNull('center_id')->update(['center_id'=>$this->centerId(),'updated_at'=>now()]);DB::table('assignments')->where('id',$id)->update(['status'=>'offered','updated_at'=>now()]);});return back()->with('success','Pickup verified and sent to rider.');}
 public function parcels(){return view('center_parcels',['links'=>app(CommonController::class)->links(),'parcels'=>DB::table('parcels as p')->join('orders as o','o.id','=','p.order_id')->join('addresses as a','a.id','=','o.address_id')->where(function($q){$q->where('p.center_id',$this->centerId())->orWhere(function($q){$q->where('p.status','PICKED_UP')->where('p.center_id',$this->centerId());});})->select('p.*','a.city','a.province')->orderByDesc('p.id')->paginate(20),'areas'=>DB::table('delivery_areas')->where('center_id',$this->centerId())->get()]);}
 public function receive(Request $r,int $id){$p=DB::table('parcels')->find($id);abort_unless($p&&$p->status==='PICKED_UP'&&$p->center_id===$this->centerId(),422);Workflow::move($id,'AT_SORTING_CENTER',auth()->id(),null,null,$this->centerId());return back()->with('success','Parcel scanned at center.');}
 public function sort(Request $r,int $id){$v=$r->validate(['area_id'=>'required|exists:delivery_areas,id']);$p=DB::table('parcels')->find($id);abort_unless($p&&$p->center_id===$this->centerId(),403);$area=DB::table('delivery_areas')->find($v['area_id']);$order=DB::table('orders')->where('id',$p->order_id)->first();$address=DB::table('addresses')->find($order->address_id);abort_unless($area->center_id===$this->centerId()&&strcasecmp($area->city,$address->city)===0&&strcasecmp($area->province,$address->province)===0,422,'Area must match the buyer address.');Workflow::move($id,'SORTED',auth()->id(),null,$area->id,$this->centerId());return back()->with('success','Parcel sorted.');}
 public function assign(int $id){$p=DB::table('parcels')->find($id);abort_unless($p&&$p->center_id===$this->centerId()&&in_array($p->status,['SORTED','DELIVERY_FAILED']),403);$area=DB::table('delivery_areas')->find($p->delivery_area_id);abort_unless($area&&$area->rider_id&&DB::table('users')->where('id',$area->rider_id)->where('active',1)->where('approval_status','approved')->exists(),422);DB::transaction(function()use($p,$area){DB::table('assignments')->where('parcel_id',$p->id)->where('kind','delivery')->where('status','accepted')->update(['status'=>'failed','updated_at'=>now()]);DB::table('assignments')->insert(['parcel_id'=>$p->id,'rider_id'=>$area->rider_id,'kind'=>'delivery','status'=>'offered','earnings'=>50,'created_at'=>now(),'updated_at'=>now()]);Workflow::move($p->id,'ASSIGNED_TO_RIDER',auth()->id(),null,null,$this->centerId());});return back()->with('success','Assigned to area rider.');}
 public function returned(int $id){Workflow::move($id,'RETURNED',auth()->id(),null,null,$this->centerId());return back()->with('success','Returned.');}
 public function report(){return $this->listing('Parcel report',DB::table('parcels')->where('center_id',$this->centerId()));}
 public function assignments(){return view('rider_assignments',['links'=>app(CommonController::class)->links(),'assignments'=>DB::table('assignments as s')->join('parcels as p','p.id','=','s.parcel_id')->join('orders as o','o.id','=','p.order_id')->join('addresses as a','a.id','=','o.address_id')->where('s.rider_id',auth()->id())->select('s.*','p.status as parcel_status','a.city','a.province')->orderByDesc('s.id')->paginate(20)]);}
 public function accept(int $id){$a=DB::table('assignments')->where('id',$id)->where('rider_id',auth()->id())->where('status','offered')->first();abort_unless($a,403);DB::table('assignments')->where('id',$id)->update(['status'=>'accepted','updated_at'=>now()]);return back()->with('success','Assignment accepted.');}
 public function riderStep(Request $r,int $id){$v=$r->validate(['status'=>'required|in:PICKED_UP,OUT_FOR_DELIVERY,DELIVERED,DELIVERY_FAILED','reason'=>'required_if:status,DELIVERY_FAILED|nullable|string|max:2000']);Workflow::move($id,$v['status'],auth()->id(),$v['reason']??null);return back()->with('success','Parcel updated.');}
 public function earnings(){return $this->listing('Completed trips and earnings',DB::table('assignments')->where('rider_id',auth()->id())->where('status','completed'));}
}
