<?php
namespace App\Http\Controllers;
use App\Services\Workflow;
use Illuminate\Routing\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class SellerController extends Controller {
 private function list($title,$query){return view('list',['title'=>$title,'links'=>app(CommonController::class)->links(),'records'=>$query->orderByDesc('id')->paginate(20)]);}
 public function products(){return view('seller_products',['links'=>app(CommonController::class)->links(),'products'=>DB::table('products')->where('seller_id',auth()->id())->orderByDesc('id')->paginate(20),'categories'=>DB::table('categories')->get()]);}
 public function addProduct(Request $r){$v=$r->validate(['name'=>'required|max:180','description'=>'nullable|string','category_id'=>'required|exists:categories,id','price'=>'required|numeric|min:0.01','discount_percent'=>'required|numeric|between:0,100','stock'=>'required|integer|min:0']);DB::table('products')->insert($v+['seller_id'=>auth()->id(),'approved'=>0,'active'=>1,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Product submitted for review.');}
 public function updateProduct(Request $r,int $id){$v=$r->validate(['name'=>'required|max:180','price'=>'required|numeric|min:0.01','stock'=>'required|integer|min:0','discount_percent'=>'required|numeric|between:0,100']);abort_unless(DB::table('products')->where('id',$id)->where('seller_id',auth()->id())->exists(),403);DB::table('products')->where('id',$id)->update($v+['approved'=>0,'updated_at'=>now()]);return back()->with('success','Updated; awaiting review.');}
 public function addVariation(Request $r,int $id){$v=$r->validate(['name'=>'required|max:120','price_adjustment'=>'required|numeric','stock'=>'required|integer|min:0']);abort_unless(DB::table('products')->where('id',$id)->where('seller_id',auth()->id())->exists(),403);DB::table('product_variations')->insert($v+['product_id'=>$id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Variation added.');}
 public function orders(){return view('seller_orders',['links'=>app(CommonController::class)->links(),'riders'=>DB::table('users')->where('role','rider')->where('approval_status','approved')->where('active',1)->get(),'orders'=>DB::table('orders as o')->join('parcels as p','p.order_id','=','o.id')->where('o.seller_id',auth()->id())->select('o.*','p.id as parcel_id')->orderByDesc('o.id')->paginate(20)]);}
 public function transition(Request $r,int $id){$v=$r->validate(['status'=>'required|in:CONFIRMED,PREPARING,READY_FOR_PICKUP']);$p=DB::table('parcels')->where('order_id',$id)->first();abort_unless($p,404);Workflow::move($p->id,$v['status'],auth()->id());return back()->with('success','Status updated.');}
 public function voucher(Request $r){$v=$r->validate(['code'=>'required|max:60|unique:vouchers,code','discount_percent'=>'required|numeric|between:0,100','expires_at'=>'nullable|date|after:now']);DB::table('vouchers')->insert($v+['seller_id'=>auth()->id(),'active'=>1,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Voucher created.');}
 public function pickup(Request $r,int $id){$v=$r->validate(['rider_id'=>'required|exists:users,id']);$p=DB::table('parcels')->where('order_id',$id)->first();abort_unless($p&&DB::table('orders')->where('id',$id)->where('seller_id',auth()->id())->exists(),403);abort_unless($p->status==='PREPARING',422);abort_unless(DB::table('users')->where('id',$v['rider_id'])->where('role','rider')->where('approval_status','approved')->where('active',1)->exists(),422);abort_if(DB::table('assignments')->where('parcel_id',$p->id)->where('kind','pickup')->exists(),422);DB::table('assignments')->insert(['parcel_id'=>$p->id,'rider_id'=>$v['rider_id'],'kind'=>'pickup','status'=>'requested','earnings'=>30,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Pickup rider requested.');}
 public function label(int $id){$o=DB::table('orders')->where('id',$id)->where('seller_id',auth()->id())->first();abort_unless($o,404);return view('label',['order'=>$o,'parcel'=>DB::table('parcels')->where('order_id',$id)->first(),'address'=>DB::table('addresses')->find($o->address_id)]);}
 public function report(){return view('list',['title'=>'Sales and commission','links'=>app(CommonController::class)->links(),'records'=>DB::table('orders')->where('seller_id',auth()->id())->whereIn('status',['DELIVERED','COMPLETED'])->paginate(30)]);}
}
