<?php
namespace App\Http\Controllers;
use App\Services\Workflow;
use Illuminate\Routing\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class ShopController extends Controller {
 private function links(){return app(CommonController::class)->links();}
 public function landing(){$b=fn()=>DB::table('products')->where('products.active',1)->where('products.approved',1);return view('landing',['featured'=>$b()->join('categories','categories.id','=','products.category_id')->select('products.*','categories.name as category')->orderByDesc('products.id')->limit(8)->get(),'categories'=>DB::table('categories')->get(),'stats'=>['products'=>$b()->count(),'sellers'=>DB::table('users')->where('role','seller')->where('approval_status','approved')->where('active',1)->count(),'orders'=>DB::table('orders')->whereIn('status',['DELIVERED','COMPLETED'])->count()],'notice'=>DB::table('announcements')->orderByDesc('id')->first()]);}
 public function home(Request $r){$q=DB::table('products')->join('categories','categories.id','=','products.category_id')->select('products.*','categories.name as category')->where('products.active',1)->where('products.approved',1);if($r->filled('q'))$q->where('products.name','like','%'.$r->q.'%');if($r->filled('category'))$q->where('category_id',$r->integer('category'));return view('shop',['products'=>$q->paginate(12),'categories'=>DB::table('categories')->get()]);}
 public function product(int $id){$product=DB::table('products')->where('id',$id)->where('active',1)->where('approved',1)->first();abort_unless($product,404);return view('product',['p'=>$product,'variations'=>DB::table('product_variations')->where('product_id',$id)->get()]);}
 public function cart(){return view('cart',['links'=>$this->links(),'rows'=>DB::table('cart_items as c')->join('products as p','p.id','=','c.product_id')->leftJoin('product_variations as v','v.id','=','c.variation_id')->where('c.buyer_id',auth()->id())->select('c.*','p.name','p.price','p.discount_percent','p.seller_id','v.name as variation','v.price_adjustment')->get(),'addresses'=>DB::table('addresses')->where('user_id',auth()->id())->get()]);}
 public function add(Request $r){$v=$r->validate(['product_id'=>'required|exists:products,id','variation_id'=>'nullable|exists:product_variations,id','quantity'=>'required|integer|min:1|max:100']);$p=DB::table('products')->where('id',$v['product_id'])->where('active',1)->where('approved',1)->first();abort_unless($p,404);if(isset($v['variation_id']))abort_unless(DB::table('product_variations')->where('id',$v['variation_id'])->where('product_id',$p->id)->exists(),422);DB::table('cart_items')->insert(['buyer_id'=>auth()->id(),'product_id'=>$p->id,'variation_id'=>$v['variation_id']??null,'quantity'=>$v['quantity'],'created_at'=>now(),'updated_at'=>now()]);return redirect('/cart')->with('success','Added to cart.');}
 public function address(Request $r){$v=$r->validate(['recipient'=>'required|max:150','phone'=>'required|max:40','street'=>'required|max:200','barangay'=>'required|max:120','city'=>'required|max:120','province'=>'required|max:120','postal_code'=>'nullable|max:20']);DB::table('addresses')->insert($v+['user_id'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Address saved.');}
 public function checkout(Request $r){$v=$r->validate(['address_id'=>'required|integer','payment_method'=>'required|in:cod,manual','voucher'=>'nullable|string|max:60']);abort_unless(DB::table('addresses')->where('id',$v['address_id'])->where('user_id',auth()->id())->exists(),403);
  $ids=DB::table('cart_items')->where('buyer_id',auth()->id())->pluck('id');abort_if($ids->isEmpty(),422,'Cart is empty');
  $orderIds=DB::transaction(function()use($ids,$v){$rows=DB::table('cart_items')->whereIn('id',$ids)->where('buyer_id',auth()->id())->lockForUpdate()->get();$groups=[];
   foreach($rows as $row){$p=DB::table('products')->where('id',$row->product_id)->lockForUpdate()->first();abort_unless($p&&$p->active&&$p->approved,422,'Product unavailable');$variation=$row->variation_id?DB::table('product_variations')->where('id',$row->variation_id)->where('product_id',$p->id)->lockForUpdate()->first():null;abort_if($row->variation_id&&!$variation,422);abort_if($row->quantity>($variation?$variation->stock:$p->stock)||$row->quantity>$p->stock,422,'Not enough stock');$price=round(((float)$p->price+(float)($variation->price_adjustment??0))*(1-(float)$p->discount_percent/100),2);$groups[$p->seller_id][]=['row'=>$row,'product'=>$p,'variation'=>$variation,'price'=>$price];}
   $voucher=null;if(!empty($v['voucher'])){$voucher=DB::table('vouchers')->where('code',$v['voucher'])->where('active',1)->where(function($q){$q->whereNull('expires_at')->orWhere('expires_at','>',now());})->first();if(!$voucher)throw ValidationException::withMessages(['voucher'=>'Voucher invalid or expired.']);if($voucher->seller_id && (count($groups)!==1||!isset($groups[$voucher->seller_id])))throw ValidationException::withMessages(['voucher'=>'Voucher is only for its seller.']);}
   $created=[];foreach($groups as $sellerId=>$items){$subtotal=array_sum(array_map(fn($x)=>$x['row']->quantity*$x['price'],$items));$discount=round($subtotal*(float)($voucher->discount_percent??0)/100,2);$total=round($subtotal-$discount,2);$oid=DB::table('orders')->insertGetId(['buyer_id'=>auth()->id(),'seller_id'=>$sellerId,'address_id'=>$v['address_id'],'status'=>'PLACED','total'=>$total,'discount'=>$discount,'commission'=>round($total*.1,2),'voucher_id'=>$voucher->id??null,'created_at'=>now(),'updated_at'=>now()]);$created[]=$oid;
   foreach($items as $x){$row=$x['row'];$p=$x['product'];DB::table('products')->where('id',$p->id)->decrement('stock',$row->quantity);if($x['variation'])DB::table('product_variations')->where('id',$x['variation']->id)->decrement('stock',$row->quantity);DB::table('order_items')->insert(['order_id'=>$oid,'product_id'=>$p->id,'variation_id'=>$row->variation_id,'name'=>$p->name.' '.($x['variation']->name??''),'quantity'=>$row->quantity,'unit_price'=>$x['price'],'created_at'=>now(),'updated_at'=>now()]);}
   DB::table('payments')->insert(['order_id'=>$oid,'method'=>$v['payment_method'],'status'=>$v['payment_method']==='cod'?'due_on_delivery':'awaiting_manual_confirmation','amount'=>$total,'created_at'=>now(),'updated_at'=>now()]);$pid=DB::table('parcels')->insertGetId(['order_id'=>$oid,'tracking_code'=>'LKS-'.strtoupper(Str::random(12)),'status'=>'PLACED','created_at'=>now(),'updated_at'=>now()]);DB::table('status_history')->insert(['parcel_id'=>$pid,'from_status'=>null,'to_status'=>'PLACED','actor_id'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);DB::table('notifications')->insert(['user_id'=>$sellerId,'body'=>'New order #'.$oid,'created_at'=>now(),'updated_at'=>now()]);}
   DB::table('cart_items')->whereIn('id',$ids)->where('buyer_id',auth()->id())->delete();return $created;});return redirect('/orders')->with('success','Order placed: '.implode(', ',$orderIds));}
 public function orders(){return view('orders',['links'=>$this->links(),'orders'=>DB::table('orders as o')->join('parcels as p','p.order_id','=','o.id')->where('o.buyer_id',auth()->id())->select('o.*','p.id as parcel_id','p.tracking_code','p.failure_reason')->orderByDesc('o.id')->get()]);}
 public function confirm(Request $r,int $id){$p=DB::table('parcels')->where('order_id',$id)->first();abort_unless($p,404);Workflow::move($p->id,'COMPLETED',auth()->id());return back()->with('success','Order completed.');}
 public function rating(Request $r,int $id){$v=$r->validate(['stars'=>'required|integer|between:1,5','comment'=>'nullable|string|max:2000']);abort_unless(DB::table('orders')->where('id',$id)->where('buyer_id',auth()->id())->where('status','COMPLETED')->exists(),403);DB::table('ratings')->updateOrInsert(['order_id'=>$id],$v+['buyer_id'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Review saved.');}
}
