CREATE DATABASE IF NOT EXISTS lokashop_erp_demo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lokashop_erp_demo;
CREATE TABLE migrations (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,migration VARCHAR(255) NOT NULL,batch INT NOT NULL);
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,phone VARCHAR(40) NULL,password VARCHAR(255) NOT NULL,role VARCHAR(30) NOT NULL,approval_status VARCHAR(20) NOT NULL DEFAULT 'pending',active BOOLEAN NOT NULL DEFAULT TRUE,vehicle VARCHAR(120) NULL,remember_token VARCHAR(100) NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE registration_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,kind VARCHAR(40) NOT NULL,path VARCHAR(255) NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE seller_businesses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL UNIQUE,name VARCHAR(180) NOT NULL,category VARCHAR(100) NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE sorting_centers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL UNIQUE,name VARCHAR(180) NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE delivery_areas (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,center_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,city VARCHAR(120) NOT NULL,province VARCHAR(120) NOT NULL,rider_id BIGINT UNSIGNED NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(center_id) REFERENCES sorting_centers(id),FOREIGN KEY(rider_id) REFERENCES users(id));
CREATE TABLE addresses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,recipient VARCHAR(150) NOT NULL,phone VARCHAR(40) NOT NULL,street VARCHAR(200) NOT NULL,barangay VARCHAR(120) NOT NULL,city VARCHAR(120) NOT NULL,province VARCHAR(120) NOT NULL,postal_code VARCHAR(20) NULL,is_default BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL UNIQUE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE products (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,seller_id BIGINT UNSIGNED NOT NULL,category_id BIGINT UNSIGNED NOT NULL,name VARCHAR(180) NOT NULL,description TEXT NULL,price DECIMAL(12,2) NOT NULL,discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0,stock INT NOT NULL DEFAULT 0,approved BOOLEAN NOT NULL DEFAULT TRUE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(seller_id) REFERENCES users(id),FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE product_variations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,price_adjustment DECIMAL(12,2) NOT NULL DEFAULT 0,stock INT NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE cart_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,variation_id BIGINT UNSIGNED NULL,quantity INT NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(buyer_id) REFERENCES users(id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(variation_id) REFERENCES product_variations(id));
CREATE TABLE vouchers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,seller_id BIGINT UNSIGNED NULL,code VARCHAR(60) NOT NULL UNIQUE,discount_percent DECIMAL(5,2) NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,expires_at DATETIME NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(seller_id) REFERENCES users(id));
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL,seller_id BIGINT UNSIGNED NOT NULL,address_id BIGINT UNSIGNED NOT NULL,status VARCHAR(40) NOT NULL,total DECIMAL(12,2) NOT NULL,discount DECIMAL(12,2) NOT NULL DEFAULT 0,commission DECIMAL(12,2) NOT NULL DEFAULT 0,voucher_id BIGINT UNSIGNED NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(buyer_id) REFERENCES users(id),FOREIGN KEY(seller_id) REFERENCES users(id),FOREIGN KEY(address_id) REFERENCES addresses(id),FOREIGN KEY(voucher_id) REFERENCES vouchers(id));
CREATE TABLE order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,variation_id BIGINT UNSIGNED NULL,name VARCHAR(180) NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(12,2) NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,method VARCHAR(30) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',amount DECIMAL(12,2) NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE parcels (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL UNIQUE,tracking_code VARCHAR(50) NOT NULL UNIQUE,status VARCHAR(40) NOT NULL,center_id BIGINT UNSIGNED NULL,delivery_area_id BIGINT UNSIGNED NULL,failure_reason TEXT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(center_id) REFERENCES sorting_centers(id),FOREIGN KEY(delivery_area_id) REFERENCES delivery_areas(id));
CREATE TABLE assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,parcel_id BIGINT UNSIGNED NOT NULL,rider_id BIGINT UNSIGNED NOT NULL,kind VARCHAR(20) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'offered',earnings DECIMAL(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(parcel_id) REFERENCES parcels(id),FOREIGN KEY(rider_id) REFERENCES users(id));
CREATE TABLE status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,parcel_id BIGINT UNSIGNED NOT NULL,from_status VARCHAR(40) NULL,to_status VARCHAR(40) NOT NULL,actor_id BIGINT UNSIGNED NOT NULL,reason TEXT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(parcel_id) REFERENCES parcels(id),FOREIGN KEY(actor_id) REFERENCES users(id));
CREATE TABLE ratings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL UNIQUE,buyer_id BIGINT UNSIGNED NOT NULL,stars TINYINT NOT NULL,comment TEXT NULL,seller_response TEXT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,sender_id BIGINT UNSIGNED NOT NULL,recipient_id BIGINT UNSIGNED NOT NULL,body TEXT NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(sender_id) REFERENCES users(id),FOREIGN KEY(recipient_id) REFERENCES users(id));
CREATE TABLE notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,body TEXT NOT NULL,read_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE complaints (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NOT NULL,description TEXT NOT NULL,resolution TEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'open',created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE announcements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,body TEXT NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE policies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,body TEXT NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
INSERT INTO migrations (migration,batch) VALUES ('2026_01_01_000000_create_lokashop_schema',1);
INSERT INTO users (id,name,email,phone,password,role,approval_status,active,created_at,updated_at) VALUES
(1,'Demo Buyer','buyer@lokashop.test','09000000001','$2b$12$bDTUmgl3bCnOHt3zRsM.suUoqgQXslTMAJgcp/Lb75MSoe7RUN2ZK','buyer','approved',1,NOW(),NOW()),
(2,'Demo Seller','seller@lokashop.test','09000000002','$2b$12$bDTUmgl3bCnOHt3zRsM.suUoqgQXslTMAJgcp/Lb75MSoe7RUN2ZK','seller','approved',1,NOW(),NOW()),
(3,'Demo Admin','admin@lokashop.test','09000000003','$2b$12$bDTUmgl3bCnOHt3zRsM.suUoqgQXslTMAJgcp/Lb75MSoe7RUN2ZK','admin','approved',1,NOW(),NOW()),
(4,'Demo Sorting Center','sorting_center@lokashop.test','09000000004','$2b$12$bDTUmgl3bCnOHt3zRsM.suUoqgQXslTMAJgcp/Lb75MSoe7RUN2ZK','sorting_center','approved',1,NOW(),NOW()),
(5,'Demo Rider','rider@lokashop.test','09000000005','$2b$12$bDTUmgl3bCnOHt3zRsM.suUoqgQXslTMAJgcp/Lb75MSoe7RUN2ZK','rider','approved',1,NOW(),NOW());
INSERT INTO seller_businesses (user_id,name,category,created_at,updated_at) VALUES (2,'Green Goods','Home',NOW(),NOW());
INSERT INTO sorting_centers (id,user_id,name,created_at,updated_at) VALUES (1,4,'Laguna Center',NOW(),NOW());
INSERT INTO delivery_areas (id,center_id,name,city,province,rider_id,created_at,updated_at) VALUES (1,1,'Area A','Santa Cruz','Laguna',5,NOW(),NOW());
INSERT INTO addresses (id,user_id,recipient,phone,street,barangay,city,province,postal_code,is_default,created_at,updated_at) VALUES (1,1,'Demo Buyer','09000000001','12 Main Street','Poblacion','Santa Cruz','Laguna','4009',1,NOW(),NOW());
INSERT INTO categories (id,name,created_at,updated_at) VALUES (1,'Home',NOW(),NOW());
INSERT INTO products (id,seller_id,category_id,name,description,price,stock,created_at,updated_at) VALUES (1,2,1,'Reusable Bag','Reusable green shopping bag',199.00,30,NOW(),NOW());
INSERT INTO product_variations (id,product_id,name,price_adjustment,stock,created_at,updated_at) VALUES (1,1,'Forest green',0,15,NOW(),NOW()),(2,1,'Bright green',0,15,NOW(),NOW());
INSERT INTO vouchers (seller_id,code,discount_percent,active,created_at,updated_at) VALUES (2,'GREEN10',10,1,NOW(),NOW());
INSERT INTO announcements (title,body,created_at,updated_at) VALUES ('Welcome','Welcome to LokaShop.',NOW(),NOW());
