name: lokashop_rider
description: "LokaShop rider app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/rider_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/rider_logo.png

