<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{CommonController as C,ShopController as S,SellerController as V,AdminController as A};
Route::get('/',[S::class,'landing']);Route::get('/shop',[S::class,'home']);Route::get('/product/{id}',[S::class,'product']);
Route::get('/track/{code}',[C::class,'track']);
Route::get('/login',[C::class,'authForm'])->name('login');Route::post('/login',[C::class,'login']);Route::get('/register',[C::class,'authForm']);Route::post('/register',[C::class,'register']);
Route::middleware('auth')->group(function(){Route::post('/logout',[C::class,'logout']);Route::get('/dashboard',[C::class,'dashboard']);Route::get('/profile',[C::class,'profile']);Route::post('/profile',[C::class,'updateProfile']);Route::get('/messages',[C::class,'messages']);Route::post('/messages',[C::class,'sendMessage']);});
Route::middleware(['auth','role:buyer'])->group(function(){Route::get('/cart',[S::class,'cart']);Route::post('/cart',[S::class,'add']);Route::post('/addresses',[S::class,'address']);Route::post('/checkout',[S::class,'checkout']);Route::get('/orders',[S::class,'orders']);Route::post('/orders/{id}/confirm',[S::class,'confirm']);Route::post('/orders/{id}/rating',[S::class,'rating']);});
Route::middleware(['auth','role:seller'])->prefix('seller')->group(function(){Route::get('/products',[V::class,'products']);Route::post('/products',[V::class,'addProduct']);Route::post('/products/{id}',[V::class,'updateProduct']);Route::post('/products/{id}/variations',[V::class,'addVariation']);Route::get('/orders',[V::class,'orders']);Route::get('/orders/{id}/label',[V::class,'label']);Route::post('/orders/{id}/status',[V::class,'transition']);Route::post('/orders/{id}/pickup',[V::class,'pickup']);Route::post('/vouchers',[V::class,'voucher']);Route::get('/reports',[V::class,'report']);});
Route::middleware(['auth','role:admin'])->prefix('admin')->group(function(){Route::get('/approvals',[A::class,'approvals']);Route::get('/documents/{id}',[A::class,'document']);Route::post('/approvals/{id}',[A::class,'approve']);Route::get('/users',[A::class,'users']);Route::post('/users/{id}/toggle',[A::class,'toggle']);Route::get('/products',[A::class,'products']);Route::post('/products/{id}',[A::class,'productDecision']);Route::get('/reports',[A::class,'report']);Route::get('/announcements',[A::class,'announcements']);Route::post('/announcements',[A::class,'announcement']);Route::get('/complaints',[A::class,'complaints']);Route::post('/complaints/{id}',[A::class,'resolve']);});

Route::middleware(['auth','role:buyer'])->group(function(){Route::get('/complaints',fn()=>view('complaints',['links'=>app(C::class)->links(),'complaints'=>\Illuminate\Support\Facades\DB::table('complaints')->where('user_id',auth()->id())->get()]));Route::post('/complaints',function(\Illuminate\Http\Request $r){$v=$r->validate(['order_id'=>'required|integer','description'=>'required|string|max:3000']);abort_unless(\Illuminate\Support\Facades\DB::table('orders')->where('id',$v['order_id'])->where('buyer_id',auth()->id())->exists(),403);\Illuminate\Support\Facades\DB::table('complaints')->insert($v+['user_id'=>auth()->id(),'status'=>'open','created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Complaint sent.');});});
